server:
  port: 80
  servlet:
    context-path: /wx_1901

spring:
  datasource:
    url: jdbc:mysql://39.96.59.235/wx_1901
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Xiaoluo301817.
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:config/mapper/**.xml



